apiVersion: apps/v1
kind: Deployment
metadata:
  name: switch52-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: switch52
  template:
    metadata:
      labels:
        app: switch52
    spec:
      containers:
      - name: myapp
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/myapp
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: switch52-config
        - secretRef:
            name: firebase-credentials
