type EmployeeDTO {
    employeeOid: String
    
    employeeId: Int
    name: String
    email: String
    position: String
    phone: String
    joindate: String
    department: String

    groupId: ID 
    supervisorName: String
    supervisorOid: String
    isSupervisor: Boolean

    locationId: ID
    workplace: String
    workhour: String
    workhourOn: String
    workhourOff: String
    workhourHalf: String

    dayoffPerYear: Int
}
type Employee{
    _id: ID
    employeeId: Int
    name: String
    email: String
    position: String
    phone: String
    joindate: String
    groupId: ID 
    locationId: ID
    dayoffPerYear: Int
}
input EmployeeInput {
    employeeId: Int
    name: String
    email: String
    position: String
    phone: String
    joindate: String
    groupId: ID
    locationId: ID
    dayoffPerYear: Int
}
type Group {
    _id: ID
    groupName: String
    groupSupervisorOid: String
    parentGroupId: ID 
}

type Attendance {
    _id: ID
    date: String
    checkInTime: String #original Type Date
    checkOutTime: String #original Type Date
    locationId: String
    status: Boolean
    employeeOid: String
}

type Location {
    _id: ID
    workplace: String
    workhourOn: String
    workhourOff: String
    workhourHalf: String
}
type Dayoff {
    _id: ID
    employeeOid:String
    dayoffType: String!
    requestComment: String
    dayoffDate: String!
    requestStatus: String
    requestDate: String
    supervisorOid: String
    requestKey: String
}
type Holiday {
    holidayName: String!     # Name of the holiday
    holidayDate: String!     # Date of the holiday in 'yyyy-MM-dd' format
}

type AttendanceHistory {
    employeeOid: String
    date: String
    locationId: String
    checkInTime: String
    checkOutTime: String
    status: Boolean
    checkInStatus: String
    checkOutStatus: String
    workTypeList: [String!]
    workduration: String
}
type DayoffHistory {
    dayoffType: String!
    requestComment: String!
    dayoffDateText: String!
    requestStatus: String
    requestDate: String
    supervisorOid: String
    requestKey: String
}
type EmployeeValDTO {
    employeeOid: String!
    employeeName: String!
    isSupervisor: Boolean!
    currentlyMarked: Boolean

}
type AttendanceStatusAndDetailsDTO{
    status: Boolean
    workTypeList: [String!]
    startTime:String!
    endTime:String!
    locationName:String!
}
type AttendanceStatusDTO {
    status: Boolean!

}
type RequestDTO {
    employeeOid: String
    employeeName: String!
    requestType: String!
    requestStatus: String!
    supervisorOid: String!
    requestKey: String!

    requestDate: String!
    requestComment: String!
    
    dayoffDateText: String
    dayoffType: String
    
}

type LocationInfoDTO {
    workplace: String!
    workhourOn: String!
    workhourOff: String!
    workhourHalf: String!
}
type DayoffInfoDTO {
    supervisorName: String!
    supervisorOid: String!
    dayoffRemaining: Int!
    holidayList: [Holiday!]!    # List of holidays
}
type GroupMembersDTO {
  groupName: String!
  groupId: String
  parentGroupId: String
  groupSupervisorOid: String
  members: [EmployeeDTO!]!
}
type Query {
    validateUidAndPhone(uid: String!, phone: String!): EmployeeValDTO
    #getObjectIdByPhone(phone: String!): Employee
    
    getAttendanceStatusAndDetails(employeeOid: String! ): AttendanceStatusAndDetailsDTO
    getAttendanceStatus(employeeOid: String!): AttendanceStatusDTO
    getEmployeeDayoff(employeeOid: String!,startDate: String!, endDate: String!,requestStatusList: [String!]): [DayoffHistory]
    

    getPendingRequests(employeeOid:String!): [RequestDTO]
    getRequestHistory(employeeOid: String!, startDate: String!, endDate: String!, requestStatusList: [String!]): [RequestDTO]
    
    getEmployeeInfo(employeeOid: String!): EmployeeDTO
    getLocationInfo(employeeOid: String!): LocationInfoDTO
    getDayoffInfo(employeeOid: String!): DayoffInfoDTO
    getEmployeeAttendance(employeeOid: String!,startDate: String!, endDate: String!, workTypeList:[String!]): [AttendanceHistory]
    
    getMyAllGroupsMembers(employeeOid: String!): [GroupMembersDTO]
    getMyAllGroups(employeeOid: String!): [Group]
    
    getAllLocations: [Location]
    getAllEmployees: [Employee]
    getAllDayoffs: [Dayoff]
    getAllAttendances: [Attendance]
    getAllGroups: [Group]
}
type Mutation {
    markAttendance(employeeOid: String!, status: Boolean!): AttendanceStatusDTO
    requestDayoff(employeeOid: String!, dateList: [String!], dayoffType: String!, requestComment: String!,beforeDateRemaining:Int!):[String!]
    answerRequest(employeeOid: String!, requestStatus: String!, answerComment: String!, requestKey: String!):Boolean
    saveFCMToken(employeeOid: String!, fcmToken: String!):Boolean

    sendNotification(token: String!, title: String!, message:String!): String
    sendNotificationToSupervisor(employeeOid: String!, title: String!, message:String!, pageKey:String!): String
    sendNotificationToEmployeeOid(employeeOid: String!,  title: String!,  message: String!, pageKey:String!): String

    updateEmployee(employeeOid: String!, employeeInput: EmployeeInput!): String
}
