type Employee {
    #_id: ID
    employeeId: Int
    name: String
    email: String
    position: String
    phone: String
    joindate: String

    #groupId: ID # groupId
    department: String
    supervisorName: String
    supervisorOid: String
    isSupervisor: Boolean

    locationId: ID
    workplace: String
    workhour: String
    workhourOn: String
    workhourOff: String
    workhourHalf: String

    dayoffPerYear: Int
}

type Group {
    groupName: String
    groupSupervisorOid: String
    subgroup: [ID] 
    parentGroup: ID 
}

type Attendance {
    employeeOid: String
    date: String
    checkInTime: String
    checkOutTime: String
    location: String
    status: Boolean
    checkInStatus: String
    checkOutStatus: String
    workTypeList: [String!]
}

type Location {
    workplace: String
    workhourOn: String
    workhourOff: String
    workhourHalf: String
}
type Dayoff {
    dayoffType: String!
    requestComment: String
    dayoffDate: String!
    requestStatus: String
    requestDate: String
    supervisorOid: String
    requestKey: String
}


type AttendanceHistory {
    employeeOid: String
    date: String
    locationId: String
    checkInTime: String
    checkOutTime: String
    status: Boolean
    checkInStatus: String
    checkOutStatus: String
    workTypeList: [String!]
    workduration: String
}
type DayoffHistory {
    dayoffType: String!
    requestComment: String!
    dayoffDateText: String!
    requestStatus: String
    requestDate: String
    supervisorOid: String
    requestKey: String
}
type EmployeeValDTO {
    employeeOid: String!
    employeeName: String!
    isSupervisor: Boolean!
    currentlyMarked: Boolean

}
type AttendanceStatusAndDetailsDTO{
    status: Boolean
    workTypeList: [String!]
    startTime:String!
    endTime:String!
    locationName:String!
}
type AttendanceStatusDTO {
    status: Boolean!

}
type RequestDTO {
    employeeOid: String
    employeeName: String!
    requestType: String!
    requestStatus: String!
    supervisorOid: String!
    requestKey: String!

    requestDate: String!
    requestComment: String!
    
    dayoffDateText: String
    dayoffType: String
    
}

type LocationInfoDTO {
    workplace: String!
    workhourOn: String!
    workhourOff: String!
    workhourHalf: String!
}
type DayoffInfoDTO {
    supervisorName: String!
    supervisorOid: String!
    dayoffRemaining: Int!
}
type GroupMembersDTO {
  groupName: String!
  members: [Employee!]!
}
type Query {
    validateUidAndPhone(uid: String!, phone: String!): EmployeeValDTO
    getObjectIdByPhone(phone: String!): Employee
    
    getAttendanceStatusAndDetails(employeeOid: String! ): AttendanceStatusAndDetailsDTO
    getAttendanceStatus(employeeOid: String!): AttendanceStatusDTO
    getEmployeeDayoff(employeeOid: String!,startDate: String!, endDate: String!,requestStatusList: [String!]): [DayoffHistory]
    

    getPendingRequests(employeeOid:String!): [RequestDTO]
    getRequestHistory(employeeOid: String!, startDate: String!, endDate: String!, requestStatusList: [String!]): [RequestDTO]
    
    getEmployeeInfo(employeeOid: String!): Employee
    getLocationInfo(employeeOid: String!): LocationInfoDTO
    getDayoffInfo(employeeOid: String!): DayoffInfoDTO
    getEmployeeAttendance(employeeOid: String!,startDate: String!, endDate: String!, workTypeList:[String!]): [AttendanceHistory]
    
    getMyAllGroupsMembers(employeeOid: String!): [Employee]
}
type Mutation {
    markAttendance(employeeOid: String!, status: Boolean!): AttendanceStatusDTO
    requestDayoff(employeeOid: String!, dateList: [String!], dayoffType: String!, requestComment: String!,beforeDateRemaining:Int!):[String!]
    answerRequest(employeeOid: String!, requestStatus: String!, answerComment: String!, requestKey: String!):Boolean
    saveFCMToken(employeeOid: String!, fcmToken: String!):Boolean

    sendNotification(token: String!, title: String!, message:String!): String
    sendNotificationToSupervisor(employeeOid: String!, title: String!, message:String!, pageKey:String!): String
    sendNotificationToEmployeeOid(employeeOid: String!,  title: String!,  message: String!, pageKey:String!): String
}
